Types of Inheritance
neildhale/Cpp-TutorialCenter pull request #7
Opened 2022-07-13 07:16 UTC by cbabhulkar

Kindly review

2022-07-13 07:36 UTC, neildhale commented on InheritanceTypes/multilevelinheritance.cpp
> +class person:public student{
Person ===> class name

2022-07-13 07:38 UTC, neildhale commented on InheritanceTypes/multipleinheritance.cpp
> +class Institute:public Staff,public Student{
comment how order of constructor and destructor called !!!!

2022-07-13 07:40 UTC, neildhale commented on InheritanceTypes/singlelevelinheritance.cpp
> +	int id;
I know if there is no any specifier then it is private but it is good if we mention access specifier

2022-07-13 07:41 UTC, neildhale requested changes
Please address review comments.

2022-07-13 11:03 UTC, neildhale commented on InheritanceTypes/multipleinheritance.cpp
> +	void Entry(){
here function name start with capital letter and  Staff::void display() start with small letter. please decide one approach for function name defination. I would suggest function name should start with small letter. if the name is to bit the you can add capital letter e.g. getStaffEntry().  display() or displayStaffDetail().

2022-07-18 12:19 UTC, cbabhulkar commented on InheritanceTypes/multipleinheritance.cpp
> +	void Entry(){
Done

2022-07-18 17:24 UTC, neildhale approved these changes

2022-07-19 08:55 UTC, merged